project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: "fintrack-api/src/main/resources/i18n/messages*.properties"
    translation: "fintrack-api/src/main/resources/i18n/messages%locale_with_underscore%.properties"
    languages_mapping:
      locale_with_underscore:
        - "nl"
        - "de"
  - source: "fintrack-api/src/main/resources/i18n/ValidationMessages*.properties"
    translation: "fintrack-api/src/main/resources/i18n/ValidationMessages%locale_with_underscore%.properties"
    languages_mapping:
      locale_with_underscore:
        - "nl"
        - "de"