project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: "src/main/resources/i18n/messages.properties"
    translation: "src/main/resources/i18n/messages_%two_letters_code%.properties"
  - source: "src/main/resources/i18n/ValidationMessages.properties"
    translation: "src/main/resources/i18n/ValidationMessages_%two_letters_code%.properties"
