datasources:
  default:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_SCHEMA:fintrack}?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER:fintrack}
    password: ${DATABASE_PASSWORD:fintrack}
    dialect: mysql

jpa:
  default:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
flyway:
  datasources:
    default:
      locations: ["classpath:db/camunda/mysql", "classpath:db/migration/mysql"]
      validate-on-migrate: false
