datasources:
  default:
    url: jdbc:h2:file:${micronaut.application.storage.location}/db/personal_finance_db;DB_CLOSE_DELAY=1000;MODE=MariaDB;IGNORECASE=TRUE
    driverClassName: org.h2.Driver
    username: ${DATABASE_USER:fintrack}
    password: ${DATABASE_PASSWORD:fintrack}
    dialect: mysql

flyway:
  datasources:
    default:
      locations: ["classpath:db/camunda/h2", "classpath:db/migration"]
