openapi: 3.1.0
info:
  title: Pledger.io System API
  version: 3.0.0
  contact:
    name: Jong Soft Development
    url: https://github.com/pledger-io/rest-application
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

tags:
  - name: i18n
    description: i18n
  - name: account-fetcher
    description: Operations to fetch account information
  - name: account-commands
    description: Operations to manipulate account information
  - name: transaction-fetcher
    description: Operations to fetch transaction information

security:
  - bearerAuth: []

paths:
# OpenID Connect discovery
  /.well-known/openid-connect: { $ref: './paths/well-known-openid-connect.yaml' }
  /.well-known/public-key: { $ref: './paths/well-known-public-key.yaml' }

# User account operations
  /v2/api/user-account: { $ref: './paths/user-account.yaml' }
  /v2/api/user-account/verify-2-factor: { $ref: './paths/user-account-verify-2-factor.yaml' }
  /v2/api/user-account/{user}: { $ref: './paths/user-account-by-name.yaml' }
  /v2/api/user-account/{user}/sessions: { $ref: './paths/user-account-sessions.yaml' }
  /v2/api/user-account/{user}/sessions/{session}: { $ref: './paths/user-account-session-by-id.yaml' }
  /v2/api/user-account/{user}/2-factor: { $ref: './paths/user-account-2-factor.yaml' }

# Export operations
  /v2/api/export: { $ref: './paths/export.yaml' }
  /v2/api/import: { $ref: './paths/import.yaml' }

# Language support operations
  /v2/api/i18n/{languageCode}: { $ref: './paths/i18n.yaml' }

# Currency-related operations
  /v2/api/currencies: { $ref: './paths/currencies.yaml' }
  /v2/api/currencies/{currencyCode}: { $ref: './paths/currency-by-code.yaml' }

# Application configuration operations
  /v2/api/settings: { $ref: './paths/settings.yaml' }
  /v2/api/settings/{setting}: { $ref: './paths/settings-by-name.yaml' }

# Files operations
  /v2/api/files: { $ref: './paths/files.yaml' }
  /v2/api/files/{fileCode}: { $ref: './paths/files-by-code.yaml' }

# Bank account-related operations
  /v2/api/account-types: { $ref: './paths/account-types.yaml' }
  /v2/api/accounts: { $ref: './paths/accounts.yaml' }
  /v2/api/accounts/top-by-spending: { $ref: './paths/accounts-top-by-spending.yaml' }
  /v2/api/accounts/{id}: { $ref: './paths/accounts-by-id.yaml' }
  /v2/api/accounts/{id}/saving-goals: { $ref: './paths/accounts-saving-goals.yaml' }
  /v2/api/accounts/{id}/saving-goals/{goalId}: { $ref: './paths/accounts-saving-goals-by-id.yaml' }
  /v2/api/accounts/{id}/saving-goals/{goalId}/make-reservation: { $ref: './paths/accounts-saving-goals-reservation.yaml' }
  /v2/api/accounts/{id}/reconcile: { $ref: './paths/accounts-reconcile.yaml' }

# Contract operations
  /v2/api/contracts: { $ref: './paths/contracts.yaml' }
  /v2/api/contracts/{id}: { $ref: './paths/contracts-by-id.yaml' }
  /v2/api/contracts/{id}/warn-before-expiration: { $ref: './paths/contracts-warn-before-expiration.yaml' }

# Tag operations
  /v2/api/tags: { $ref: './paths/tags.yaml' }
  /v2/api/tags/{tag}: { $ref: './paths/tags-by-id.yaml' }

# Category operations
  /v2/api/categories: { $ref: './paths/categories.yaml' }
  /v2/api/categories/{id}: { $ref: './paths/categories-by-id.yaml' }

# Transaction operations
  /v2/api/transactions: { $ref: './paths/transactions.yaml' }
  /v2/api/transactions/{id}: { $ref: './paths/transactions-by-id.yaml' }

# Transaction schedule operations
  /v2/api/schedules: { $ref: './paths/schedules.yaml' }
  /v2/api/schedules/{id}: { $ref: './paths/schedules-by-id.yaml' }

# Budget operations
  /v2/api/budgets: { $ref: './paths/budgets.yaml' }
  /v2/api/budgets/expenses: { $ref: './paths/budgets-expenses.yaml' }
  /v2/api/budgets/expenses/balance: { $ref: './paths/budgets-expenses-balance.yaml' }

# Balance operations
  /v2/api/balance: { $ref: './paths/balance.yaml' }
  /v2/api/balance/{partition}: { $ref: './paths/balance-by-partition.yaml' }
  /v2/api/balance/by-date/{type}: { $ref: './paths/balance-by-type.yaml' }

# Spending operations
  /v2/api/detected/insight: { $ref: './paths/detected-insight.yaml' }
  /v2/api/detected/pattern: { $ref: './paths/detected-pattern.yaml' }

# Batch importer operations
  /v2/api/batch-importer: { $ref: './paths/batch-importer.yaml' }
  /v2/api/batch-importer/{slug}: { $ref: './paths/batch-importer-by-slug.yaml' }
  /v2/api/batch-importer/{slug}/tasks: { $ref: './paths/batch-importer-by-slug-tasks.yaml' }
  /v2/api/batch-importer-config: { $ref: './paths/batch-importer-config.yaml' }

# Suggestions rule operations
  /v2/api/transaction-rules: { $ref: './paths/transaction-rules.yaml' }
  /v2/api/transaction-rules/{group}: { $ref: './paths/transaction-rules-group.yaml' }
  /v2/api/transaction-rules/{group}/{ruleId}: { $ref: './paths/transaction-rules-rule.yaml' }

  /v2/api/ai/auto-complete: { $ref: './paths/ai-auto-complete.yaml' }
  /v2/api/ai/extract: { $ref: './paths/ai-extract.yaml' }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    400: { $ref: './responses/400-response.yaml' }
    401: { $ref: './responses/401-response.yaml' }
    403: { $ref: './responses/403-response.yaml' }
    404: { $ref: './responses/404-response.yaml' }

  parameters:
    offset: { $ref: './parameters/offset.yaml' }
    number-of-results: { $ref: './parameters/number-of-results.yaml' }
    start-date: { $ref: 'parameters/startDate.yaml' }
    end-date: { $ref: 'parameters/endDate.yaml' }
    name-filter: { $ref: 'parameters/name.yaml' }
    account-filter: { $ref: 'parameters/accounts.yaml' }
    expense-filter: { $ref: 'parameters/expenses.yaml' }
    category-filter: { $ref: 'parameters/categories.yaml' }
    contract-filter: { $ref: 'parameters/contracts.yaml' }
    tag-filter: { $ref: 'parameters/tags.yaml' }
    import-slug-filter: { $ref: 'parameters/import-id.yaml' }

  schemas:
    date-range: { $ref: './components/date-range.yaml' }
    periodicity: { $ref: './components/periodicity.yaml' }
    account-link: { $ref: './components/account-link.yaml' }
    paged-response: { $ref: './components/paged-response.yaml' }
    account-type: { $ref: './components/account-type.yaml' }
    rule-column: { $ref: 'components/rule-column.yaml' }
    operation-type: { $ref: 'components/operation-type.yaml' }

    user-request: { $ref: './components/request/user.yaml' }
    token-request: { $ref: './components/request/token.yaml' }
    session-request: { $ref: './components/request/session.yaml' }
    patch-multi-factor-request: { $ref: './components/request/patch-multi-factor.yaml' }
    currency-request: { $ref: './components/request/currency.yaml' }
    currency-patch-request: { $ref: './components/request/currency-patch.yaml' }
    setting-request: { $ref: './components/request/setting.yaml' }
    account-request: { $ref: './components/request/account.yaml' }
    account-reconcile-request: { $ref: './components/request/account-reconcile.yaml' }
    saving-goal-request: { $ref: './components/request/saving-goal.yaml' }
    saving-reservation-request: { $ref: './components/request/saving-goal-reservation.yaml' }
    contract-request: { $ref: './components/request/contract.yaml' }
    category-request: { $ref: './components/request/category.yaml' }
    transaction-request: { $ref: './components/request/transaction.yaml' }
    transaction-schedule-request: { $ref: './components/request/transaction-schedule.yaml' }
    transaction-schedule-patch-request: { $ref: './components/request/transaction-schedule-patch.yaml' }
    budget-request: { $ref: './components/request/budget.yaml' }
    expense-request: { $ref: './components/request/expense.yaml' }
    balance-request: { $ref: './components/request/balance.yaml' }
    rule-request: { $ref: './components/request/transaction-rule.yaml' }
    rule-group-patch-request: { $ref: './components/request/transaction-rule-group-patch.yaml' }

    user-profile-response: { $ref: './components/response/user-profile.yaml' }
    export-profile-response: { $ref: 'components/response/export-profile.yaml' }
    session-response: { $ref: './components/response/session.yaml' }
    i18n-response: { $ref: './components/response/i18n.yaml' }
    currency-response: { $ref: './components/response/currency.yaml' }
    setting-response: { $ref: './components/response/setting.yaml' }
    file-response: { $ref: './components/response/file.yaml' }
    account-response: { $ref: './components/response/account.yaml' }
    account-paged-response: { $ref: './components/response/accounts-paged.yaml' }
    account-spending-response: { $ref: './components/response/account-spending.yaml' }
    account-reconcile-response: { $ref: './components/response/account-reconciled.yaml' }
    saving-goal-response: { $ref: './components/response/saving-goal.yaml' }
    schedule-response: { $ref: './components/response/schedule.yaml' }
    contract-response: { $ref: './components/response/contract.yaml' }
    category-response: { $ref: './components/response/category.yaml' }
    category-paged-response: { $ref: './components/response/categories-paged.yaml' }
    transaction-response: { $ref: './components/response/transaction.yaml' }
    transaction-paged-response: { $ref: './components/response/transaction-paged.yaml' }
    transaction-schedule-response: { $ref: './components/response/transaction-schedule.yaml' }
    extracted-transaction-response: { $ref: './components/response/extracted-transaction.yaml' }
    budget-response: { $ref: './components/response/budget.yaml' }
    expense-response: { $ref: './components/response/expense.yaml' }
    expense-computed-response: { $ref: './components/response/expense-computed.yaml' }
    balance-response: { $ref: './components/response/balance.yaml' }
    balance-partitioned-response: { $ref: './components/response/balance-partitioned.yaml' }
    balance-dated-response: { $ref: './components/response/balance-dated.yaml' }
    detected-insight-response: { $ref: './components/response/detected-insight.yaml' }
    detected-pattern-response: { $ref: './components/response/detected-pattern.yaml' }
    batch-job-response: { $ref: './components/response/batch-job.yaml' }
    batch-job-paged-response: { $ref: './components/response/batch-job-paged.yaml' }
    batch-configuration-response: { $ref: './components/response/batch-configuration.yaml' }
    rule-response: { $ref: './components/response/transaction-rule.yaml' }
    rule-group-response: { $ref: './components/response/transaction-rule-group.yaml' }
    task-response: { $ref: './components/response/task.yaml' }

    enable-mfa-request:
      type: object
      required:
        - action
        - verificationCode
      properties:
        verificationCode:
          type: string
          min: 4
          max: 8
        action:
          type: string
    disable-mfa-request:
      type: object
      required:
        - action
      properties:
        action:
          type: string
