openapi: 3.1.0
info:
  title: Pledger.io Learning Rule API
  version: 3.0.0
  contact:
    name: Jong Soft Development
    url: https://github.com/pledger-io/rest-application
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

security:
  - bearerAuth: [ ]

paths:


components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    400: { $ref: './responses/400-response.yaml' }
    401: { $ref: './responses/401-response.yaml' }
    403: { $ref: './responses/403-response.yaml' }
    404: { $ref: './responses/404-response.yaml' }

  schemas:
    rule-group-response: { $ref: '#/components/schemas/rule-group' }
    rule-group:
      type: object
      required: [ name, sort ]
      properties:
        sort:
          type: integer
          format: int32
        name:
          type: string

    rule-column: { $ref: 'components/rule-column.yaml' }
    operation-type: { $ref: 'components/operation-type.yaml' }

    create-rule-group-request: { $ref: 'components/request/create-rule-group.yaml' }
    patch-rule-group-request: { $ref: 'components/request/patch-rule-group.yaml' }
    rule-request: { $ref: 'components/request/rule.yaml' }

    rule-response: { $ref: 'components/response/rule.yaml' }
    extracted-response: { $ref: 'components/response/extracted-transaction.yaml' }
