datasources:
  default:
    url: jdbc:h2:mem:FinTrack;DB_CLOSE_DELAY=50;MODE=MariaDB
    driverClassName: org.h2.Driver
    username: ${DATABASE_USER:fintrack}
    password: ${DATABASE_PASSWORD:fintrack}
    migration-locations: ["classpath:db/camunda/h2", "classpath:db/migration"]
    dialect: mysql


micronaut:
  application:
    storage:
      location: ./build/resources/test
  server:
    log-handled-exceptions: true
