-- Budget table
ALTER TABLE budget ALTER COLUMN b_from TYPE TIMESTAMP, ALTER COLUMN b_from DROP NOT NULL, ALTER COLUMN b_from SET DEFAULT NULL;
ALTER TABLE budget ALTER COLUMN b_until TYPE TIMESTAMP, ALTER COLUMN b_until DROP NOT NULL, ALTER COLUMN b_until SET DEFAULT NULL;

-- Import table
ALTER TABLE import ALTER COLUMN created TYPE TIMESTAMP, ALTER COLUMN created SET NOT NULL, ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE import ALTER COLUMN finished TYPE TIMESTAMP, ALTER COLUMN finished DROP NOT NULL, ALTER COLUMN finished SET DEFAULT NULL;

-- Transaction_journal table
ALTER TABLE transaction_journal ALTER COLUMN created TYPE TIMESTAMP, ALTER COLUMN created SET NOT NULL, ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE transaction_journal ALTER COLUMN updated TYPE TIMESTAMP, ALTER COLUMN updated SET NOT NULL, ALTER COLUMN updated SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE transaction_journal ALTER COLUMN deleted TYPE TIMESTAMP, ALTER COLUMN deleted DROP NOT NULL, ALTER COLUMN deleted SET DEFAULT NULL;
ALTER TABLE transaction_journal ALTER COLUMN t_date TYPE TIMESTAMP, ALTER COLUMN t_date DROP NOT NULL, ALTER COLUMN t_date SET DEFAULT NULL;
ALTER TABLE transaction_journal ALTER COLUMN interest_date TYPE TIMESTAMP, ALTER COLUMN interest_date DROP NOT NULL, ALTER COLUMN interest_date SET DEFAULT NULL;
ALTER TABLE transaction_journal ALTER COLUMN book_date TYPE TIMESTAMP, ALTER COLUMN book_date DROP NOT NULL, ALTER COLUMN book_date SET DEFAULT NULL;

-- Transaction_part table
ALTER TABLE transaction_part ALTER COLUMN created TYPE TIMESTAMP, ALTER COLUMN created SET NOT NULL, ALTER COLUMN created SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE transaction_part ALTER COLUMN updated TYPE TIMESTAMP, ALTER COLUMN updated SET NOT NULL, ALTER COLUMN updated SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE transaction_part ALTER COLUMN deleted TYPE TIMESTAMP, ALTER COLUMN deleted DROP NOT NULL, ALTER COLUMN deleted SET DEFAULT NULL;

