application:
  ai:
    engine: ${AI_ENGINE:jlama}
    temperature: 0.0

    jlama:
      # alternative models can be found here: https://huggingface.co/tjake
      model: tjake/Llama-3.2-1B-Instruct-JQ4
    openai:
      model: gpt-4o-mini
      key: ${OPENAI_TOKEN}