application:
  ai:
    engine: ${AI_ENGINE:ollama}
    temperature: 0.2

    ollama:
      model: qwen2.5:7b
      uri: http://localhost:11434
    openai:
      model: gpt-4o-mini
      key: ${OPENAI_TOKEN}