application:
  ai:
    engine: ${AI_ENGINE:jlama}
    temperature: 0.0

    jlama:
      # alternative models can be found here: https://huggingface.co/tjake
      model: nttaii/llmlingua-2-bert-base-multilingual-cased-meetingbank
    openai:
      model: gpt-4o-mini
      key: ${OPENAI_TOKEN}