name: Build flow

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Build the application
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: 'check'
      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            **/build/classes/**
            **/build/libs/*.jar
            **/build/reports/jacoco/test/*.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: |
            **/build/test-results/**