name: Translations sync

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-translations:
    name: Sync with Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sync with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          download_translations: true
          localization_branch_name: l10n_translations
          create_pull_request: true
          pull_request_base_branch_name: 'master'
          pull_request_reviewers: 'gjong'
          pull_request_labels: 'enhancement'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}